version: "3"

services:
  web:
    build: .
    image: "leoimpacta/myfirstapp:4.0"
    environment:
      - MESSAGE=Usando a variavel do desafio!
    networks:
      labdocker:
        ipv4_address: 172.20.0.10
    ports:
      - "80:80"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/srv/redis/data:/data"
    command: "redis-server --appendonly yes"
    networks:
      labdocker:
        ipv4_address: 172.20.0.11

networks:
  labdocker:
    ipam:
      config:
        - subnet: 172.20.0.0/24
